#!/bin/bash

set -euf -o pipefail

# input validation

if [[ $# -ne 1 ]]; then
  echo "usage: $0 file-to-upload" 1>&2
  exit 1
fi

inpath="$1"
filename=`basename "$inpath"`

if [ ! -f "$inpath" ]; then
  echo "$inpath: No such file or not a file" 1>&2
  exit 1
fi

# configuration
user="kevin"
remote="files.kevinchen.co"
webroot="/var/www/files.kevinchen.co/public_html/temp"
baseurl="https://files.kevinchen.co/temp"

# build paths
uuid=`uuidgen`
# On macOS, UUIDs are given in uppercase
# source: http://stackoverflow.com/a/2264537/1489823
uuid=`echo "$uuid" | awk '{print tolower($0)}'`

remote_dirpath="$webroot/$uuid"
remote_filepath="$remote_dirpath/$filename"
url="$baseurl/$uuid/$filename"

# upload the file
sftp "$user"@"$remote" 1>&2 <<EOF
mkdir "$remote_dirpath"
put "$inpath" "$remote_filepath"
chmod 644 "$remote_filepath"
EOF

# output the result
# no need to check sftp's error because of the `set -e`
echo "$url"
